export const INCREASE_COUNT = 'INCREASE_COUNT';
export const DECREASE_COUNT = 'DECREASE_COUNT';
export const RESET_COUNT = 'RESET_COUNT';
export const FETCH_VALUTE_REQUEST = 'FETCH_VALUTE_REQUEST';
export const FETCH_VALUTE_SUCCESS = 'FETCH_VALUTE_SUCCESS';
export const FETCH_VALUTE_ERROR = 'FETCH_VALUTE_ERROR';

